accounts/urls.py
from . import views
from django.urls import path

app_name = "accounts"

urlpatterns = [
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('signup/', views.signup, name="signup"),
    path('<str:username>/', views.profile, name="profile"),
]

todos/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views

app_name = "todos"
urlpatterns = [
    path('', TemplateView.as_view(template_name='todos/app.html'), name="index"),
    path('lists/', views.lists_list, name="lists_list"),
    path('lists/<int:pk>/', views.lists_detail, name="lists_detail"),
    path('todos/', views.todos_list, name="todos_list"),
    path('todos/<int:pk>/', views.todos_detail, name="todos_detail"),
    path('todos/<int:pk>/check/', views.todos_check, name="todos_check"),
    path('todos/<int:pk>/important/', views.todos_important, name="todos_important"),
    path('todos/<int:pk>/details/', views.details_list, name="details_list"),
    path('details/<int:pk>/', views.details_detail, name="details_detail"),
]

wookslist/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('todos.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
]

templates/_footer.html
<!-- .Footer -->
<footer class="footer">
  <div class="content has-text-centered">
    <p>
      <a href="https://github.com/jiwookseo/wookslist" class="has-text-primary">Wookslist<a/> <span style="color: white;">made by Jiwook Seo. <br/>
      The source code is licensed MIT. <br/></span>
    </p>
  </div>
</footer>
<!-- /.Footer -->

templates/_nav.html
<!-- .Nav -->
{% load static %}
<nav class="navbar is-white" id="nav" style="padding-top: 0.6rem;">
  <div class="container is-fluid">
    <div class="navbar-brand">
      <div class="navbar-item">
        <img
            @mouseover="logo='https://wookslist.herokuapp.com/static/image/logo2.png'"
            @mouseleave="logo='https://wookslist.herokuapp.com/static/image/logo1.png'"
            :src="logo" @click="goHome">
      </div>
      <span class="navbar-burger burger"
            @click="showNav = !showNav"
            :class="{ 'is-active': showNav }"
            data-target="navbarMenuHeroA">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </span>
    </div>
    <div id="navbarMenuHeroA" class="navbar-menu has-background-white" :class="{ 'is-active': showNav }">
      <div class="navbar-end">
        {% if user.is_active %}
          <span class="navbar-item">
            <a class="button is-primary is-outlined" href="{% url 'accounts:logout' %}">
              <span>Logout</span>
            </a>
          </span>
          <span class="navbar-item">
            <a class="button is-primary" href="{% url 'todos:index' %}">
              <span>sign in by {{ user.username }}</span>
            </a>
          </span>
        {% else %}
          <span class="navbar-item">
            <a class="button is-primary is-outlined" href="{% url 'accounts:signup' %}">
              <span>Sign up</span>
            </a>
          </span>
          <span class="navbar-item">
            <a class="button is-primary" href="{% url 'accounts:login' %}">
              <span>Login</span>
            </a>
          </span>
        {% endif %}
      </div>
    </div>
  </div>
</nav>
<script>
  const nav = new Vue({
    el: '#nav',
    data: {
      logo: 'https://wookslist.herokuapp.com/static/image/logo1.png',
      showNav: false,
      query: '',
    },
    methods: {
      goHome: function () {
        window.location.replace("{% url 'todos:index' %}")
      }
    },
  });
</script>
<!-- /.Nav -->

templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width,initial-scale=1.0">
  <!-- og tag -->
  <meta property="og:title" content="ㅇㅅㄹㅅㅌ">
  <meta property="og:url" content="https://wookslist.herokuapp.com/">
  <meta property="og:site_name" content="ㅇㅅㄹㅅㅌ Wookslist">
  <meta property="og:description" content="Plan Your Life and Never Be Stuck Again">
  <meta property="og:image"
        content="https://wookslist.herokuapp.com/static/image/og_image.png?raw=true">
  <!-- favicon -->
  <link rel="icon"
        href="https://wookslist.herokuapp.com/static/image/favicon.ico">
  <!-- Bulma -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.4/css/bulma.min.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma-calendar@6.0.6/dist/css/bulma-calendar.min.css">
  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Gugi|Noto+Sans+KR:300,400,700" rel="stylesheet">
  <!-- My CSS files -->
  <link rel="stylesheet"
        href="https://wookslist.herokuapp.com/static/css/app.css">
  <!-- Vue -->
  <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
  <!-- Axios -->
  <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
  <title>ㅇㅅㄹㅅㅌ</title>
</head>
<body>
{% include '_nav.html' %}
<div id="app">
  {% block app %}{% endblock %}
</div>
{% include '_footer.html' %}
<!-- Bulma extensions -->
<script src="https://cdn.jsdelivr.net/npm/bulma-calendar@6.0.6/dist/js/bulma-calendar.min.js"></script>
{% block script %}{% endblock %}
<!-- Font Awesome -->
<script defer src="https://use.fontawesome.com/releases/v5.8.2/js/all.js"></script>
</body>
</html>